name: guardiantest
description: Guardian Test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase: ^7.3.3
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  get_it: ^5.0.3
  device_info: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
